/* ============================================================
   MISSION CONTROL - predefined resume Q&A

   Deterministic knowledge base: no API calls. Each entry has
   aliases so fuzzy matching can map natural questions to answers.
============================================================ */
const MISSION_QA=[
  {id:'overview',category:'Profile',q:'Give me a quick overview of Aryan.',aliases:['who is aryan','tell me about aryan','overview','summary','profile'],a:"Aryan Satghare is a BSc (Honors) Computer Science student at Heriot-Watt University in Dubai, on track for First-Class Honors with a US GPA equivalent of 4.0/4.0. His resume combines full-stack engineering, concurrent systems, AI problem solving, UI/UX leadership, and technical communication. He is expected to graduate in 2027."},
  {id:'education',category:'Education',q:'What is Aryan studying and how is he performing academically?',aliases:['education','academic performance','grades','gpa','university','what does aryan study'],a:"Aryan is studying BSc (Honors) Computer Science at Heriot-Watt University. He maintained a straight-A record across all eight Year 3 courses, achieved up to 90% in technical coursework, and reports a continuous First-Class profile across the majority of core modules in Years 1 and 2. His resume lists a US GPA equivalent of 4.0/4.0 and expected graduation in 2027."},
  {id:'courses',category:'Education',q:'What relevant courses has Aryan taken?',aliases:['courses','modules','subjects','coursework'],a:"Relevant coursework on Aryan's resume includes Artificial Intelligence and Intelligent Agents, Database Management Systems, Data Communications and Networking, Data Structures and Algorithms, Hardware-Software Interface, Language Processors, Operating Systems & Concurrency, Software Development, User-Centered Experimental Design, and Web Programming."},
  {id:'award',category:'Education',q:'What academic award has Aryan received?',aliases:['award','honors','honours','deputy principal'],a:"Aryan received Heriot-Watt University's Deputy Principal's Award for Academic Excellence. The resume states that it was awarded for securing First-Class / Grade A marks across six distinct core computing modules during the 2023–2024 academic session."},
  {id:'projects',category:'Projects',q:'What projects has Aryan built?',aliases:['projects','project portfolio','what has he built'],a:"Aryan highlights three main projects: LivSync, a full-stack health companion application; CPUScheduler, a concurrent multi-threaded Java CPU scheduler; and a Sudoku Solver that models Sudoku as an AI Constraint Satisfaction Problem. Together they cover product engineering, security, databases, concurrency, algorithm design, and AI search."},
  {id:'livsync',category:'Projects',q:'Tell me about LivSync.',aliases:['livsync','health app','wellness platform','full stack health'],a:"LivSync is a responsive, role-based hybrid wellness platform that unifies wearable data and biometrics into interactive tracking tools. Aryan's resume describes a Next.js 14, React 18, and Tailwind CSS frontend backed by PostgreSQL and Prisma ORM, with Recharts dashboards plus jsPDF and html2canvas export pipelines. The project was delivered in a cross-functional Agile/Scrum team across five core experience and security modules."},
  {id:'security',category:'Projects',q:'How did Aryan handle security and authentication in LivSync?',aliases:['security','authentication','2fa','bcrypt','speakeasy','livsync security'],a:"For LivSync, Aryan engineered an authentication pipeline using Bcrypt password hashing, middleware route protection, session cookies, and a Two-Factor Authentication workflow implemented with Speakeasy. These are the security mechanisms explicitly listed on his resume."},
  {id:'cpu',category:'Projects',q:'Tell me about Aryan\'s concurrent CPU Scheduler.',aliases:['cpu scheduler','cpuscheduler','concurrency project','locks','reentrantlock','conditions','fcfs','sjf'],a:"CPUScheduler is a multi-threaded Java execution engine for coordinating heterogeneous compute resources under thread contention. Aryan implemented the Monitor Pattern using ReentrantLock and per-core Condition variables, designed a multi-burst scheduling engine, supported FCFS with head-of-line blocking mitigation and SJF policies, and built concurrent integration tests for thread lifecycle, resource interleaving, and lock safety."},
  {id:'sudoku',category:'Projects',q:'Tell me about Aryan\'s AI Sudoku Solver.',aliases:['sudoku','csp','constraint satisfaction','backtracking','forward checking'],a:"Aryan's Sudoku Solver models a 9×9 puzzle as a Constraint Satisfaction Problem in Java. It uses DFS backtracking with Forward Checking to prune search branches, runs heavy search logic away from the Java Swing UI thread, separates algorithm, presentation, and file I/O concerns, and records telemetry such as recursive calls, backtracks, and wall-clock runtime."},
  {id:'skills',category:'Skills',q:'What are Aryan\'s main technical skills?',aliases:['skills','technical skills','tech stack','languages','frameworks'],a:"Aryan lists C, Java, JavaScript, OCaml, PDDL, Python, SQL, TypeScript, ARM Assembly, HTML5, and CSS3. His frameworks and libraries include Next.js 14, React 18, Express, Tailwind CSS, Prisma ORM, Recharts, Axios, and PostCSS. Tools and databases include Docker, MySQL, PostgreSQL, Figma, Git, GitHub, GNS3, Linux commands, and Node.js."},
  {id:'backend',category:'Skills',q:'What backend and database experience does Aryan have?',aliases:['backend','database','databases','postgresql','mysql','prisma','node'],a:"Aryan's resume lists PostgreSQL, MySQL, Prisma ORM, Node.js, and Express among his backend and data tools. In LivSync specifically, he used a relational PostgreSQL database managed through Prisma ORM and built authentication utilities around Bcrypt, Speakeasy, session cookies, and route middleware."},
  {id:'ai',category:'Skills',q:'What experience does Aryan have with AI?',aliases:['ai','artificial intelligence','machine learning','chatbot','intelligent agents'],a:"Aryan's resume shows AI experience in several forms: university coursework in Artificial Intelligence and Intelligent Agents, a Sudoku solver built as an AI Constraint Satisfaction Problem, a technical workshop on AI tools beyond ChatGPT, and UI/UX work on a student-led project website featuring an AI-powered chatbot utility."},
  {id:'concurrency',category:'Skills',q:'What concurrency and multithreading experience does Aryan have?',aliases:['concurrency','multithreading','threads','threading','locks','monitor pattern'],a:"The strongest concurrency evidence is CPUScheduler: Aryan used Java ReentrantLock and per-core Condition variables with the Monitor Pattern to coordinate critical sections and precise thread wakeups under contention. His Sudoku project also involved keeping heavy search work off the Swing UI thread so the interface remained responsive."},
  {id:'leadership',category:'Experience',q:'What leadership experience does Aryan have?',aliases:['leadership','experience','team lead','ui ux','workshop'],a:"Aryan's resume lists three leadership-oriented roles: Principal UI/UX Designer for LAIRR at Heriot-Watt University, Workshop Host for the BCS Student Chapter, and Team Lead for the DormDash e-commerce group project. In DormDash, he spearheaded a five-member engineering team through the end-to-end development lifecycle from frontend to backend."},
  {id:'communication',category:'Experience',q:'What technical communication experience does Aryan have?',aliases:['communication','presentation','workshop host','speaker','seminar'],a:"As a Workshop Host for the BCS Student Chapter at Heriot-Watt University, Aryan prepared and delivered a technical seminar titled ‘The Predominant AI Tools Available Beyond ChatGPT’ for the BCS Breakout Initiative. The resume presents this as evidence of emerging-AI knowledge and technical communication."},
  {id:'design',category:'Experience',q:'What UI/UX and design experience does Aryan have?',aliases:['design','ui ux','figma','lairr','designer'],a:"Aryan served as Principal UI/UX Designer for LAIRR at Heriot-Watt University from January 2025 to January 2026. His resume says he engineered the end-to-end design system, wireframes, and aesthetic vision for a student-led project website featuring an AI-powered chatbot utility. Figma is also listed among his tools."},
  {id:'candidate',category:'Profile',q:'Why could Aryan be a strong software engineering candidate?',aliases:['strong candidate','why hire aryan','why aryan','software engineering candidate','strengths'],a:"Based strictly on the resume, Aryan combines strong academic performance with practical breadth: full-stack development in LivSync, low-level synchronization and scheduling in CPUScheduler, AI search in the Sudoku Solver, and leadership across design, technical workshops, and a five-person engineering team. That mix suggests he can move between implementation, systems thinking, collaboration, and communication."},
  {id:'contact',category:'Contact',q:'Where is Aryan based and how can I contact him?',aliases:['contact','email','phone','location','dubai','how to reach aryan'],a:"Aryan is based in Dubai, United Arab Emirates. His resume lists the email aryansatghare@hotmail.com and phone number +971 502170919. It also includes a GitHub Profile entry."}
];
/** Sidebar filter tabs for grouping questions in Mission Control. */
const MC_CATEGORIES=['All','Profile','Education','Projects','Skills','Experience','Contact'];
